version: '2'
services:
  k8s-app-monitor-agent:
    image: xiaohuih/k8s-app-monitor-agent:234d51c
    container_name: monitor-agent
    depends_on:
      - k8s-app-monitor-test
    ports:
      - 8888:8888
    environment:
      - SERVICE_NAME=k8s-app-monitor-test
  k8s-app-monitor-test:
    image: xiaohuih/k8s-app-monitor-test:9c935dd
    container_name: monitor-test
    ports:
      - 3000:3000
